services:
  mongo:
    image: mongo:8.0
    container_name: mongo-tasks
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: task_manager_db
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d